import { createApp } from 'vue'
import './style.css'
import './overrides.css'
import './hero-overrides.css'
import './achievement-overrides.css'
import './hero-layout-overrides.css'
import './system-layout-overrides.css'
import './logo-overrides.css'
import './team-text-overrides.css'
import './hero-vertical-center.css'
import './team-photo.css'
import './system-tabs.css'
import './system-tabs-motion.css'
import './system-carousel-controls.css'
import './system-preview-layout.css'
import './technology-flow.css'
import './achievement-copy.css'
import './achievement-media-layout.css'
import './team-light.css'
import './achievement-compact-layout.css'
import './system-preview-video.css'
import './try-now-button.css'
import App from './App.vue'

createApp(App).mount('#app')
